M48
; DRILL file {KiCad 9.0.7} date 2026-02-28T12:57:25+0100
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2026-02-28T12:57:25+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X5.8114Y-5.5174
X6.039Y-5.5174
T2
X5.04Y-3.56
X5.04Y-4.94
X7.57Y-3.56
X7.57Y-4.94
M30
