M48
; DRILL file {KiCad 9.0.4} date 2025-12-28T22:29:46+0100
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-12-28T22:29:46+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.4
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X5.0462Y-5.5174
X5.2738Y-5.5174
T2
X5.04Y-3.56
X5.04Y-4.94
X7.57Y-3.56
X7.57Y-4.94
M30
